### ISSUE TITLE
Ability to set sample size and start string

### ISSUE THREAD

**Issue by donaldsmith2060** [ivarprudnikov/char-rnn-tensorflow#1]
I don't see how to do this in the current ui

**Comment by ivarprudnikov** [comment]
At the moment there is no functionality to do it. Did mention it in the blog, in ["Generating sample" section](https://www.ivarprudnikov.com/run-tensorflow-scripts-nodejs-server-deployed-aws-docker-container/#generating-sample):

> As you see it is missing start_string and max_length arguments, this will be left for someone else to complete and add some input fields to UI, for now I’ve set some defaults for it to work.

**Comment by ivarprudnikov** [comment]
I'll pick details from your pull request @donaldsmith2060
